name: Redeploy Outline

on:
  workflow_dispatch:

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - run: curl --fail --show-error --silent --request POST "${{ secrets.PORTAINER_WEBHOOK_URL }}"
